name = "GothenburgBitFactory Theme"
license = "MIT"
licenselink = ""
description = ""
homepage = "https://taskwarrior.org"
tags = ["document", "bootstrap"]
features = ["document", ""]
min_version = 0.15

[author]
  name = "GothenburgBitFactory"
  homepage = "https://taskwarrior.org"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
